package Application;

import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

// TODO Make buttons functional
// TODO Consider changing the format of the buttons

/**
 * Class that controls layout and functionality of buttons to manually control the robot.
 */
class ControlsView {

    private  VBox mainLayout; // Layout generated by this class

    /**
     * Generates a total of five buttons: forward, left and right (next to each other), toggle grabber and break.
     *
     * @author Kerr
     */
    ControlsView() {
        // Create two buttons for turning left and right
        Button buttonTurnLeft = new Button("Turn Left");
        Button buttonTurnRight = new Button("Turn right");

        // Add left and right button to their own hBox
        HBox turnControls = new HBox();
        turnControls.setSpacing(10);
        turnControls.getChildren().addAll(buttonTurnLeft, buttonTurnRight);

        // Create three buttons for moving forward, grabber control and break. Set their width at MAX_value to ensure
        // alignment with other buttons.
        Button buttonForward = new Button("Forward");
        buttonForward.setMaxWidth(Double.MAX_VALUE);
        Button buttonToggleGrabber = new Button("Toggle Grabber");
        buttonToggleGrabber.setMaxWidth(Double.MAX_VALUE);
        Button buttonBreak = new Button("Break");
        buttonBreak.setMaxWidth(Double.MAX_VALUE);


        // Set basic format of the main Layout
        mainLayout = new VBox(new Label("Manual Controls"));
        mainLayout.setAlignment(Pos.CENTER);
        mainLayout.setSpacing(10);

        // Add all buttons to the mainLayout
        mainLayout.getChildren().addAll(buttonForward, turnControls, buttonToggleGrabber, buttonBreak);

        // Buttons functionality
        buttonForward.setOnAction(e -> {

        });

        buttonTurnLeft.setOnAction(e -> {

        });

        buttonTurnRight.setOnAction(e -> {

        });

        buttonToggleGrabber.setOnAction(e -> {

        });

        buttonBreak.setOnAction(e -> {

        });
    }

    /**
     * Getter method that returns the mainLayout, the layout containing all the buttons.
     * @return generated layout with five buttons for manual controls.
     *
     * @author Kerr
     */
    VBox getMainLayout() {
        return this.mainLayout;
    }
}
